// Macros for Bullet Hell

#macro BH_UI_MARGIN 50
#macro BH_TIME_PROGRESS_PERCENTAGE 0.001
#macro BH_PLAYER_POP_PROGRESS 0.01

#macro BH_PLAYER_SPEED 4
#macro BH_PLAYER_PROJECTILE_SPEED 6
#macro BH_PLAYER_PROJECTILE_DAMAGE -1
#macro BH_PLAYER_PROJECTILE_DELAY 5
#macro BH_PLAYER_HEALTH_DEFAULT 8

#macro BH_STARTING_BUBBLE_HEALTH 7
#macro BH_NUM_STARTING_BUBBLES 18 // 18 is the max with current setup
#macro BH_NUM_BUBBLES_PER_SPAWN 3
#macro BH_BUBBLE_TIME_BEFORE_POPPING 10
#macro BH_BUBBLE_MOVE_SPEED 0.7
#macro BH_MAX_BUBBLES 50
#macro BH_NUM_BUBBLE_PROJECTILES 25
#macro BH_STARTING_BUBBLE_PROJECTILE_SCALE 0.05
#macro BH_BUBBLE_PROJECTILE_SPEED 3
#macro BH_BUBBLE_PROJECTILE_DAMAGE -1

// DASH ability
#macro BH_ABILITY_DASH 1
#macro BH_DASH_DISTANCE 120
#macro BH_DASH_DURATION 8
#macro BH_DASH_COOLDOWN 120

// SHIELD ability
#macro BH_ABILITY_SHIELD 2
#macro BH_SHIELD_RADIUS 1.5
#macro BH_SHIELD_DURATION 150
#macro BH_SHIELD_COOLDOWN 600

// HEAL ability
#macro BH_ABILITY_HEAL 3
#macro BH_HEAL_AMOUNT 1
#macro BH_HEAL_COOLDOWN 1000