// Macros for Bullet Hell

#macro BH_PLAYER_SPEED 2
#macro BH_PLAYER_PROJECTILE_SPEED 4
#macro BH_PLAYER_PROJECTILE_DAMAGE -1
#macro BH_PLAYER_PROJECTILE_DELAY 5
#macro BH_PLAYER_HEALTH_DEFAULT 6

#macro BH_STARTING_BUBBLE_HEALTH 10
#macro BH_BUBBLE_FALL_SPEED 0.5
#macro BH_MAX_BUBBLES 4
#macro BH_NUM_BUBBLE_PROJECTILES 20
#macro BH_BUBBLE_PROJECTILE_SPEED 3
#macro BH_BUBBLE_PROJECTILE_DAMAGE -1

#macro BH_ABILITY_ONE 1