
// Music
#macro AUDIO_OV_MUSIC BG_music
#macro AUDIO_BH_MUSIC_SIMPLE 0
#macro AUDIO_BH_MUSIC_FULL 0

// Sound Effects
#macro AUDIO_BUBBLE_POP 0
#macro AUDIO_DAMAGE 0
#macro AUDIO_BOOST_AVAILABLE 0
#macro AUDIO_PLAYER_SHOOT mixkit_short_laser_gun_shot_1670
#macro AUDIO_GAME_OVER 0
#macro AUDIO_MENU_CLICK 0
#macro AUDIO_BUS_TRANSITION 0
#macro AUDIO_BH_TRANSITION 0