#macro DEFAULT_LEVEL		0
#macro DEFAULT_ROOM			ROOM_MENU
#macro DEFAULT_STATE		MENU
#macro DEFAULT_PREV			OVERWORLD
#macro DEFAULT_ABILITY_ONE  0

#macro DEFAULT_COMPLETION  [false, false, false, false, false, false, false]
#macro DEFAULT_BEFORE_MAIN 0
#macro DEFAULT_BUS_CHOICE BH_NO_RESPONSE
#macro DEFAULT_DIN_CHOICE BH_BATTLE_MOM